### ISSUE TITLE
rust-analyzer  build failed

### ISSUE THREAD

**Issue by antoneo** [gorules/zen#186] opened 2024-06-21 06:11 UTC
when i use the dependencies ` zen-engine = "0"`

i cant pass rust-analyzer build， but cargo run is successful.  
`
error: failed to run custom build command for `rquickjs-sys v0.4.3``

`thread 'main' panicked at C:\Users\Antoneo\.cargo\registry\src\mirrors.ustc.edu.cn-4affec411d11e50f\rquickjs-sys-0.4.3\build.rs:139:10:
  Unable to execute patch, you may need to install it: {}: Error { kind: NotFound, message: "program not found" }
  stack backtrace:`

How to fix it？

**Comment by stefan-gorules** [comment] 2024-06-24 21:39
This might be related to your operating system. Which one are you using? (Seems to be Windows) Particularly, failure is occurring because of: https://github.com/DelSkayn/rquickjs. 

Would you be able to install `patch` CLI tool? This is likely the cause as it's being called here - https://github.com/DelSkayn/rquickjs/blob/304db5d8ebe6b42cfa9d9cf6d11ff7d355bdf2ac/sys/build.rs#L247.

**Comment by stefan-gorules** [comment] 2024-07-04 10:22
@antoneo Great to hear! In case of any other problems feel free to re-open the issue. Closing this one.

**Closed by stefan-gorules** 2024-07-04 10:22 UTC
Labels: question
