### ISSUE TITLE
Hook timed out

### ISSUE THREAD

**Issue by jazarja** [gorules/zen#202] opened 2024-07-03 02:10 UTC
Not sure what is going wrong, but occasionally zenengine raise this issue:

```
thread 'tokio-runtime-worker' panicked at core/expression/src/isolate.rs:62:55:
called `Result::unwrap()` on an `Err` value: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

exception message on nodejs was **Hook timed out**

Environment:

Node.js version: 18.17.1
ZenEngine version: 0.23.0

**Comment by stefan-gorules** [comment] 2024-07-04 10:22
Hi @jazarja, would you be able to provide more details?

Reproduction steps would be useful, however the error is likely caused by loss of precision (inability to parse numbers):
https://github.com/gorules/zen/blob/4c9c26b4296fb9b6d75a46215976fbe51637ba59/core/expression/src/variable/conv.rs#L22-L24

**Comment by stefan-gorules** [comment] 2024-07-04 10:25
I'll close this in favour of #175.

**Closed by stefan-gorules** 2024-07-04 10:25 UTC
