### ISSUE TITLE
[Question] How to use API for context evaluation

### ISSUE THREAD

**Issue by josecolella** [gorules/zen#176] opened 2024-05-31 16:23 UTC
Hello team,
I'm trying out the cloud version of gorules and I am having issues trying to use the evaluate decision API endpoint. I followed the instructions in https://gorules.io/docs/brms/evaluate-decision, and the endpoint I have is

`https://jcolella.gorules.io/api/projects/b1d7297e-61e5-498d-9d2a-d5d1f7215773/evaluate/test.json`

but it returns a 404 
```
{
"message": "Route GET:/api/projects/b1d7297e-61e5-498d-9d2a-d5d1f7215773/evaluate/test.json not found",
"error": "Not Found",
"statusCode": 404
}
```

**Comment by josecolella** [comment] 2024-05-31 16:23
Is there anything I am missing?

**Comment by ivanmiletic** [comment] 2024-06-02 22:16
Hi @josecolella did you publish your decision model?

Also, API should be @POST and there should be a body with a field context

**Comment by stefan-gorules** [comment] 2024-06-24 21:34
Hi @josecolella, closing. Let us know if the issue is still present.

**Closed by stefan-gorules** 2024-06-24 21:34 UTC
